// Code generated by goctl. DO NOT EDIT.
package types

type GetUpdateResponse struct {
	Version   string `json:"version"`
	Link      string `json:"link"`
	ChangeLog string `json:"changeLog"`
}

type DoLoginReq struct {
	Secret_key string `form:"secret_key,optional"`
}

type RefreshUpdateResp struct {
	Code int `json:"code"`
}
