// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
//
// 说明：已手工剔除未使用的历史类型（DoLoginReq / VerifyJwtReq / StartContainerReq 等）。
// 重新 goctl 生成后请对照 dockercopilot.api，避免把已删除的死类型写回。

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName" validate:"required"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename" validate:"required"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag" validate:"required"`
	ContainerName   string `form:"containerName,optional"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename" validate:"required"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid" validate:"required"`
}

type IdReq struct {
	Id string `path:"id" validate:"required"`
}

type ImagePruneReq struct {
	Kind string `form:"kind,optional"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey" validate:"required"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type VersionReq struct {
	Type string `form:"type,optional"`
}
