// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName" validate:"required"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename" validate:"required"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag" validate:"required"`
	ContainerName   string `form:"containerName,optional"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name,optional"`
	NewName         string `json:"new_name" validate:"required"`
	ImageNameAndTag string `json:"image_name_and_tag" validate:"required"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename" validate:"required"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid" validate:"required"`
}

type IdReq struct {
	Id string `path:"id" validate:"required"`
}

type ImagePruneReq struct {
	Kind string `form:"kind,optional"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey" validate:"required"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	Name string `json:"name" validate:"required"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type RenameContainerReq struct {
	OldName string `json:"oldName" validate:"required"`
	NewName string `json:"newName" validate:"required"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name" validate:"required"`
}

type StopContainerReq struct {
	Name string `json:"name" validate:"required"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt" validate:"required"`
}

type VersionReq struct {
	Type string `form:"type,optional"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag" validate:"required"`
}
