// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Login "github.com/onlyLTY/oneKeyUpdate/v2/internal/handler/Login"
	containersManager "github.com/onlyLTY/oneKeyUpdate/v2/internal/handler/containersManager"
	imagesManager "github.com/onlyLTY/oneKeyUpdate/v2/internal/handler/imagesManager"
	"github.com/onlyLTY/oneKeyUpdate/v2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.IndexCheckMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: Login.DoLoginHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/login",
					Handler: Login.LoginIndexHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CookieCheckMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: containersManager.ContainersManagerIndexHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/start_container",
					Handler: containersManager.StartContainerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/stop_container",
					Handler: containersManager.StopContainerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/rename_container",
					Handler: containersManager.RenameContainerHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/containersManager"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CookieCheckMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: imagesManager.ImagesManagerIndexHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/get_new_image",
					Handler: imagesManager.GetNewImageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/imagesManager"),
	)
}
