# Generated by Django 4.2 on 2023-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255, unique=True)),
                ('local_creation_time', models.DateTimeField()),
                ('remote_last_updated_time', models.DateTimeField()),
                ('container_count', models.IntegerField(default=0)),
            ],
        ),
    ]
