# Generated by Django 4.2 on 2023-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='local_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='remote_last_updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
