# Generated by Django 4.2 on 2023-06-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_nasip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
