// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/onlyLTY/dockerCopilot/internal/handler/auth"
	compose "github.com/onlyLTY/dockerCopilot/internal/handler/compose"
	container "github.com/onlyLTY/dockerCopilot/internal/handler/container"
	icons "github.com/onlyLTY/dockerCopilot/internal/handler/icons"
	image "github.com/onlyLTY/dockerCopilot/internal/handler/image"
	progress "github.com/onlyLTY/dockerCopilot/internal/handler/progress"
	version "github.com/onlyLTY/dockerCopilot/internal/handler/version"
	"github.com/onlyLTY/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects",
				Handler: compose.CreateProjectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects",
				Handler: compose.ProjectsListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects/:id/files",
				Handler: compose.ListFilesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.ReadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.UpdateFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/validate",
				Handler: compose.ValidateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/:id/deploy/preview",
				Handler: compose.DeployPreviewHandler(serverCtx),
			},

			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/:id/deploy",
				Handler: compose.DeployHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/cleanup/preview",
				Handler: compose.CleanupPreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/cleanup",
				Handler: compose.CleanupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ports",
				Handler: compose.PortsListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update-ignore",
				Handler: container.UpdateIgnoreHandler(serverCtx, true),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/:id/update-ignore",
				Handler: container.UpdateIgnoreHandler(serverCtx, false),
			},

			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup-settings",
				Handler: container.BackupSettingsHandler,
			},
			{
				Method:  http.MethodPut,
				Path:    "/container/backup-settings",
				Handler: container.UpdateBackupSettingsHandler,
			},
			{
				Method:  http.MethodGet,
				Path:    "/settings/update-check",
				Handler: container.GetUpdateSettingsHandler,
			},
			{
				Method:  http.MethodPut,
				Path:    "/settings/update-check",
				Handler: container.UpdateUpdateSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/settings/auto-backup",
				Handler: container.GetAutoBackupSettingsHandler,
			},
			{
				Method:  http.MethodPut,
				Path:    "/settings/auto-backup",
				Handler: container.UpdateAutoBackupSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/settings/log-level",
				Handler: GetLogLevelHandler,
			},
			{
				Method:  http.MethodPut,
				Path:    "/settings/log-level",
				Handler: UpdateLogLevelHandler,
			},
			{
				Method:  http.MethodGet,
				Path:    "/settings/proxy",
				Handler: GetProxySettingsHandler,
			},
			{
				Method:  http.MethodPut,
				Path:    "/settings/proxy",
				Handler: UpdateProxySettingsHandler,
			},
			{
				Method:  http.MethodGet,
				Path:    "/logs",
				Handler: GetLogsHandler,
			},

			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/containers/check-update",
				Handler: container.CheckUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: icons.DeleteHandler(),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/images/prune",
				Handler: image.PruneHandler(serverCtx),
			},
			{
				Method: http.MethodGet,
				Path:   "/images",

				Handler: image.ImagesListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/list",
				Handler: progress.ListProgressHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
